server:
    port: 8080
#日志相关配置
logging:
  #config: classpath:logback-win.xml
  level:
      root: DEBUG  # DEBUG INFO WARN ERROR
spring:
    cloud:
      nacos:
        discovery:
          server-addr: 122.112.137.97:8849
      gateway:
        discovery:
          locator:
            lower-case-service-id: true #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
            enabled: true #表明gateway开启服务注册和发现的功能 gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
        routes:
          - id: zcloud-system-service
            url: lb://zcloud-system-service
            predicates:
              - Path=/demo/**
            filters:
              - StripPrefix=1
              - RequestTime=true